on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for opening this PR! 💙 @deep5050 will be reviewing this soon, in the mean time make sure you have followed the contribution guidelines'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
